name: Dependabot Approve and Merge

on: pull_request_target

permissions:
  pull-requests: write
  contents: write
  issues: write

jobs:
  dependabot:
    name: Auto approve and merge
    runs-on: ubuntu-latest

    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.5
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve and merge protractor
        id: auto-merge-protractor
        if: ${{contains(steps.dependabot-metadata.outputs.dependency-names, 'protractor')}}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
          echo "STATUS=true" >> $GITHUB_OUTPUT
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve and merge rxjs
        id: auto-merge-rxjs
        if: ${{contains(steps.dependabot-metadata.outputs.dependency-names, 'rxjs') && steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
          echo "STATUS=true" >> $GITHUB_OUTPUT
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Approve and merge karma
        id: auto-merge-karma
        if: ${{contains(steps.dependabot-metadata.outputs.dependency-names, 'karma') && steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
          echo "STATUS=true" >> $GITHUB_OUTPUT
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
